version: 2
executorType: docker
containerInfo:
  - image: themattrix/tox
    user: root
    cmd: ["/bin/bash"]
stages:
  build:
    workDir: ~/json_api_mapper
    steps:
      - name: Create working directory
        type: shell
        command: mkdir -p ~/json_api_mapper
        pwd: /

      - name: Install git
        type: shell
        command: |
          apt-get update
          apt-get -y install git

      - name: "Checkout code"
        type: checkout

      - name: Restore python caches
        type: cache-restore
        key: json_api_mapper-{{ .Branch }}-{{ checksum "setup.py" }}
        paths:
          - ~/json_api_mapper/.tox

      - name: Run tests
        type: shell
        command: |
          tox
          mkdir -p /tmp/test-results
          cp junit-*.xml /tmp/test-results

      - name: Save python caches
        type: cache-save
        key: json_api_mapper-{{ .Branch }}-{{ checksum "setup.py" }}
        paths:
          - ~/json_api_mapper/.tox

      - name: Save test artifacts
        type: artifacts-store
        path: /tmp/test-results
        destination: reports

      - name: Save test results
        type: test-results-store
        path: /tmp/test-results
